name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Thay đổi theo phiên bản Node.js bạn cần

      - name: Install npm dependencies
        run: npm install

      - name: Build the application
        run: npm run build # Hoặc lệnh build của bạn

      - name: Run tests
        run: npm test # Hoặc lệnh test của bạn
